goal: [1.0, 1.0]
device: "cpu"
dt: 0.05
steps: 1000

mppi: 
  device: "cpu"
  mppi_mode: "halton-spline"  # halton-spline, simple
  sampling_method: "halton"   # halton, random
  num_samples: 100
  horizon: 20                 # At least 12 for Halton Sampling
  lambda_: 0.1
  u_min: [-1.5]
  u_max: [1.5]
  noise_sigma: [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]
  update_cov: False
  rollout_var_discount: 0.95
  sample_null_action: True
  noise_abs_cost: False
  filter_u: True
  use_priors: True

simulator:
  urdf: "pointRobot.urdf"
  mode: "vel"
  render: True
